- .github/workflows/tests.yml
- tox.ini
tox is now run via Github Action. This does not fix any errors in the tests themselves!
This PR addresses #5.
> Run tox via GitHub actions

- README.rst
This change updates remaining URLs and commands that reference Mercurial and/or Bitbucket to their corresponding Git/Github versions.
I had this branch ready for a while and meant to push it earlier but I had forgotten.
> Update URLs and commands from hg/Bitbucket to git/Github

- CHANGES
I figured I'd get this started. I listed Nov 18 as the release date, but that's just a placeholder; we should substitute in whatever we want to be the actual release date before merging this.
Please go ahead and add/change anything else that should be in the changelog.
Closes #9
> Update changelog for the upcoming v0.5.1 release

- .github/workflows/tests.yml
By default, Github Actions has the fail-fast option enabled, which means that the first job to fail in a matrix causes the whole matrix to be immediately canceled. This makes it impossible to identify when a bug causing a job failure is specific to certain versions of Python. In this PR I'm setting the option to false so that each job will run to completion even if one fails.
> Disable fail-fast in Github Actions configuration

- setup.py
This commit adds `python_requires` to the setup script as recommended by https://packaging.python.org/guides/dropping-older-python-versions/. Specifically, it seems to suggest adding `python_requires` _first_ before modifying it to drop support for older versions; I guess this is so that people running older versions of Python for which support gets dropped (like 2.7) will at least find _some_ version of the package that lists itself as being compatible with that version of Python.
I plan to follow this up with another PR that drops Python 2 support, but I figured we might want to make a post release with just this change before dropping support for Python 2.
> List required Python version as 2.7 or 3.3+

- CHANGES
- pytest_localserver/__init__.py
- setup.py
This PR updates the package version to 0.5.1.post0 and adds a changelog entry. I've tentatively set the date at December 13 (Monday), and if this is approved in time, I'll push the release to PyPI then.
> Bump version to 0.5.1.post0

- .github/workflows/tests.yml
- README.rst
- setup.py
- tox.ini
This builds on #24 to drop support for Python 2, when we're ready for that.
> Drop support for older Python versions

- pyproject.toml
- pytest_localserver/__init__.py
- setup.py
- tests/test_version.py
- tox.ini
This is what I have in mind for implementing #8. I'm open to any feedback about whether we should go ahead with this.
> Use setuptools_scm for version management

- README.rst
- pytest_localserver/http.py
- tests/test_http.py
I came up with this patch set a while ago for another project of mine that was experiencing errors only when receiving chunk-encoded data. It adds the ability to serve a chunked response. I know that users can do this themselves using a custom WSGI application, but since chunking is a part of the HTTP 1.1 standard, it's a common enough use case that it _might_ be reasonable to handle it directly.
I'd be curious for your opinions @redtoad and @coordt about whether this makes sense to add to the project.
> Support chunked encoding

- pytest_localserver/smtp.py
- setup.py
- tests/test_smtp.py
I made these changes to switch from using Python's standard [smtpd](https://docs.python.org/3/library/smtpd.html) module, which is deprecated, to the external [aiosmtpd](https://aiosmtpd.readthedocs.io/en/latest/) package. The changes are somewhat substantial, but most of them are just meant to keep the Server class interface backward compatible and to support old versions of Python and smtpd. Once we drop support for older versions, it will simplify the implementation quite a bit.
One thing to note: it's not entirely clear how actively aiosmtpd is maintained, since the last commit on Github was over a year ago and there's a featured issue asking for help with the package. So I can imagine a future where the suggested replacement for smtpd changes to something other than aiosmtpd. It's …
> Use aiosmtpd for the smtp.Server class

- README.rst
I think this should be the procedure for preparing a release, based on what I remember doing for the last couple releases, and accounting for having switched to `setuptools_scm` in this latest version.
In the future we can probably automate a couple more of the steps if we want to, in particular building packages, and _maybe_ also uploading to PyPI.
> Add notes on how to release a new version to the README

- CHANGES
Everything listed under the 0.6.0 release milestone has been done (except this PR itself), so I figure it's time to release a new version. As usual, the April 27 date is just a placeholder; we should substitute in whatever we want to be the actual release date before merging this.
Anything else that should be added?
> Update changelog for the upcoming 0.6.0 release

- pyproject.toml
The `setuptools` PEP517 backend provides the dependency on `wheel`
implicitly.  The explicit dep is unnecessary and specifying it is
no longer the recommended practice per setuptools documentation.
> Remove redudant `wheel` dep from `pyproject.toml`

- setup.cfg
```
/usr/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```
> Fix a warning about dash-separated cfg key

- .github/workflows/tests.yml
- setup.py
- tests/test_smtp.py
- tox.ini
Move the aiosmtpd dependency to "smtp" extra, and handle the lack of it
gracefully in tests.  The aiosmtpd package is no longer maintained
and had major bugs that lead to it being queued for removal from Gentoo.
FWICS all packages in Gentoo that are using pytest-localserver are only
using the HTTP support.
> Make aiosmtpd dependency optional

- .github/workflows/tests.yml
Currently when someone pushes a branch directly to pytest-localserver, we get two copies of each Github action, one for the push and one for the pull request. This change should skip the pull_request action for branches pushed directly into this repository. It won't affect branches coming from other people's forks.
> Skip duplicate actions when pushing in this repository

- .github/workflows/tests.yml
- tox.ini
This expands the range of allowed pytest versions to be 6.2.4 to 7.X (inclusive), and adds some more tests to verify functionality of the package with the edge versions.
Closes #41
> Relax dependencies

- CHANGES
Everything listed under the 0.7.0 release milestone has been done (except this PR itself), so I figure it's time to release a new version. As usual, the August 30 date is just a placeholder; we should substitute in whatever we want to be the actual release date before merging this.
Anything else that should be added?
> Update changelog for the upcoming 0.7 release

- pytest_localserver/smtp.py
> Replace the _stop method, which was removed from aiosmtp 1.4.3, with the cancel_tasks method

- .github/workflows/tests.yml
This commit changes the Github Actions workflow configuration to use an older version of Ubuntu for testing on Python 3.5 and 3.6 - namely Ubuntu 20.04 instead of the current default 22.04. The runners that Github provides with Ubuntu 22.04 don't support versions of Python prior to 3.7.
We will remove support for Python <3.7 at some point, when a code change makes it necessary, but for now there happens to be nothing in the code that breaks with Python 3.5 or 3.6 and it's easy enough to support those versions, which is why I'm not removing support for them entirely yet.
I also upgraded the workflow configuration from the beta version of Python 3.11 to the final release version.
By merging this I hope to get all tests passing in #55.
> Use older Ubuntu for testing with Python 3.5 and 3.6

- setup.py
I'm adding the Python 3.11 trove classifier.
> Mark the package as being compatible with Python 3.11

- .github/workflows/release.yml
- .pre-commit-config.yaml
- README.rst
This adds a workflow for pushing to PyPI.
> Release using GitHub actions

- CHANGES
This is the last step to take before releasing version 0.7.1.
Since I forgot to do this earlier, I'm pushing the target date on the milestone to Sunday; a couple more days shouldn't hurt anything. We can release earlier if I get approvals first, though.
> Update changelog for the upcoming 0.7.1 release

- .github/workflows/release.yml
I based this change on the [official PyPI documentation](https://docs.pypi.org/trusted-publishers/) as well as a [blog post](https://pgjones.dev/blog/trusted-plublishing-2023/) walking through an example of how to implement trusted publishing for a Python project.
The diff is fairly minimal. All it does is remove the password used to authenticate to PyPI, which we don't need anymore, and add a permission needed for trusted publishing to operate.
This commit will be accompanied by some configuration in the project settings on PyPI to allow this specific workflow to act as a trusted publisher. Specifically, I'm going to add a trusted publisher with the following settings:
- Owner: `pytest-dev`
- Repository name: `pytest-localserver`
- Workflow name: `release.yml`
- Environment name: `pypi` …
> Convert to trusted publishing

- .github/workflows/release.yml
This commit changes the deployment to PyPI to be dependent on successful deployment to Test PyPI. Without this we would have to manually check that the deployment to Test PyPI succeeded before deploying to PyPI, and there's really no point in making that a manual process. (Or, a person could just deploy to PyPI directly without even waiting for the Test PyPI deployment to succeed and in that case there's no point in even deploying to Test PyPI first.)
I was inspired to do this by looking at the release workflow for some other project, but I forget which one it was.
> Make pypi deployment dependent on test-pypi deployment

- pytest_localserver/plugin.py
- pytest_localserver/smtp.py
Since none of these files are meant to be run directly as scripts, there's no need to have shebang lines in them, and in fact it could give someone a misleading impression to have them there, so removing them should reduce confusion.
Closes #47
> Remove /usr/bin/env lines

- pytest_localserver/smtp.py
`pytest_localserver.smtp` allows running itself as a module to start up an SMTP server, which is implemented by a bit of driver code guarded by an `if __name__ == "__main__"` block. Typical best practice is to put that code in a `main()` function, which is what I'm doing in this commit.
> Move SMTP driver code into a function

- pytest_localserver/http.py
- tests/test_http.py
It's possible for the _server attribute to not exist if make_server raises an error in the constructor. This usually emits some sort of additional error onto the console that can distract from identifying the real issue.
> Ignore AttributeError when shutting down server

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- setup.py
- tox.ini
This PR adds testing for Python 3.12 and adds it to the list of supported versions.
> Explicit Python 3.12 support

- README.rst
The README file had said that the SMTP server would be an instance of `smtpd.SMTPServer`, but that's actually no longer true now that we don't use the smtpd module anymore. In this commit I'm updating that bit of documentation not to specifically reference `smtpd.SMTPServer`. Instead, it's a bit vague about what kind of SMTP server is provided, only promising an API "similar to `smtpd.SMTPServer`". This gives us freedom to change the exact API offered by that class if necessary.
Closes #51
> Update README not to specify the wrong type for the SMTP server

- .gitignore
- AUTHORS
- README.rst
- pytest_localserver/http.py
- tests/test_http.py
- tests/test_https.py
> Explicitly store request data

- .pre-commit-config.yaml
- pytest_localserver/https.py
A long line in this docstring was causing the flake8 pre-commit check to fail, so I edited the comment to be compliant. I shortened the lines to about 80 characters for consistency with other comments, even though that's more of a change than is strictly required to pass flake8. With this change, we can start requiring pre-commit to pass for all merges.
I also changed a note to use Restructured Text syntax, for compatibility with other docstrings in the project.
I also changed the pre-commit configuration to skip the actionlint hook, because it's not configured to run Docker hooks.
> Fix pre-commit errors

- tox.ini
Resolves https://github.com/pytest-dev/pytest-localserver/issues/76
> Remove unused `six` from tox config

- .github/workflows/tests.yml
- pyproject.toml
- pytest_localserver/smtp.py
- setup.py
- tox.ini
Our CI jobs have stopped working with Python 3.5 since pip is no longer able to upgrade itself. Perhaps there was a recent change in PyPI's SSL certificate that makes it unable to be verified on Python 3.5, at least within GitHub Actions. Since Python 3.5 is long past EOL, we don't think it's worth putting in any work to get that job working again, so this pull request drops support for Python 3.5.
The package may still work with Python 3.5, and anyone who wants to try it is welcome to give it a go, but it's no longer officially supported and we are not putting in any effort to keep it working on 3.5 in future versions.
> Drop Python 3.5 support

- .github/workflows/tests.yml
- setup.py
- tox.ini
This PR adds testing for Python 3.13 and adds it to the list of supported versions, now that we've had the first release candidate of that version.
> Add Python 3.13 support

- .github/workflows/tests.yml
- tox.ini
We have started getting an error with `pytest>=4,<4.6` when `setuptools>=71` (or `typeguard>=4.2`) is also installed, due to a conflict with older `pytest` and `setuptools`' vendored version of `typeguard`. Out of various ways to resolve this conflict, this is the only one that doesn't involve putting an upper bound on the version of some package.
It should still be technically possible to use older versions of `pytest` along with `setuptools<71`, if someone really needs to do that, but there isn't any way to express that dependency constraint, and I'm not going to go to any trouble to support long-obsolete versions of packages.
- If I add `typeguard<4.2` to the test requirements in `tox.ini`, then I run into agronholm/typeguard#343
- If I add `setuptools<71` then everything works (since …
> Bump required pytest version to 4.6

- tox.ini
pytest 8 has been out for a while; it's long past time we officially added support for it. This will allow people to use this plugin along with pytest 8.
> Increase max allowed pytest version to 9

- .github/workflows/tests.yml
GitHub Actions is delivering errors when running tests for Python 3.7 on the latest Ubuntu runners (24.04), because Python 3.7 is not available for that runner version anymore. So I'm removing 3.7 from the list of versions tested on the latest Ubuntu and adding a test for it on Ubuntu 22.04. I gave Pypy 3.7 the same treatment. This should fix the recent CI failures.
> Run Python 3.7 tests only on Ubuntu 22.04

- README.rst
I updated the `README` with some of my own code examples and did a little cleanup/polish.
* Replace "Quickstart" section with the code for the simplest possible use-case.
* Replace `WSGI` example, as I wasn't able to get the previous example working.
* Rename the previous "Quickstart" section to "How-To".
* Rename "Available funcargs" section to "Fixtures". (That seems to be the more common term. In any case, I didn't previously know that "funcargs" was another term for "fixtures", so it may be more clear to others as well.)
* Use `code` directives instead of literal blocks to syntax highlight python code.
> Update README to provide more clear examples

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- pytest_localserver/http.py
- setup.py
- tests/test_http.py
- tox.ini
GitHub Actions has deprecated the `ubuntu-20.04` runner, and it'll be fully unsupported by 2025-04-01: https://github.com/actions/runner-images/issues/11101
I spotted this repo is still using to test Python 3.6, which has been end-of-life since 2021, so it's definitely time to drop support:
https://devguide.python.org/versions/
Python 3.7 and 3.8 are also EOL, and I recommend dropping them too. I haven't done so in this PR, but I'm happy to include it here or in a new PR if you like.
> Drop support for EOL Python 3.6

- tox.ini
Recently, version 6.2.0 of [pytest-cov](https://github.com/pytest-dev/pytest-cov) was released with support for new pluggy hookwrappers, which require `pluggy>=1.2` and `pytest>=6.2.5`, but the dependency metadata wasn't updated to reflect these requirements. There was an immediate followup release, pytest-cov 6.2.1, that fixed the metadata problem (pytest-dev/pytest-cov#200), but that still leaves version 6.2.0 as one that pip thinks should be safe to use with `pytest<6.2.5`, even though it actually isn't. (Perhaps 6.2.0 should be yanked to deal with this, but it looks like it probably won't be.)
Since some of our tests run with pytest 6.2.4, we were getting failures because of this mismatch. Accordingly, in this PR I'm manually blocking pytest-cov 6.2.0 to avoid the failure.
> Block broken version of pytest-cov

- pyproject.toml
Since the minimum required version of Python in the project's dependencies has been updated to 3.7 (see #113), it makes sense to bump the black target version to match.
> Update black target version to Python 3.7
